### ISSUE TITLE
Clouds not correct

### ISSUE THREAD

**Issue by wlbr** [matteason/daily-cloud-maps#5]
Hi, during the last 2-3 weeks the clouds seem to be squashed to the south.
Is there a way to fix that?

Thanks in advance,
Michael

**Comment by matteason** [comment]
Hi @wlbr , thanks for spotting this. It looks like the satellite data has been coming in late (or on some days not at all) so it's not available in the NASA GIBS API this project uses. The clouds that are visible are a static overlay that covers the gaps in the polar regions. 

I'll keep an eye on the [Worldview visualiser](https://worldview.earthdata.nasa.gov/?v=-270.1391960697406,-155.2432004516798,316.86333361735933,148.5764682340262&l=VIIRS_NOAA20_Clear_Sky_Confidence_Day(max=0.91),VIIRS_NOAA20_CorrectedReflectance_TrueColor,VIIRS_SNPP_CorrectedReflectance_TrueColor(hidden)&lg=false&t=2023-06-08-T11%3A52%3A23Z) today and see when the data comes in, then I might just be able to adjust the time the action runs so the data's ready in the API.

I have been investingating potential new data sources (like EUMETSAT). If the issue persists I'll look into moving over.

**Comment by wlbr** [comment]
Hey, today my Xplanet - clouds - update-script retrieved perfect clouds again!
Thanks a lot!!
<img width="1417" alt="Bildschirmfoto 2023-06-12 um 11 35 11" src="https://github.com/matteason/daily-cloud-maps/assets/741171/39d6c63c-8158-405a-8c50-5f5594e1da40">

**Comment by matteason** [comment]
Oh good! Glad it seems to be working again. I'l close this issue off but I'm continuting to look for a more reliable/faster-updating data source
