### ISSUE TITLE
Add delay in index.js to allow CLOUD_CONFIDENCE and EARTH_WITH_CLOUDS to fully load

### ISSUE THREAD

**Issue by creinemann** [matteason/daily-cloud-maps#6]
Add delay in index.js to allow CLOUD_CONFIDENCE and EARTH_WITH_CLOUDS before the rest of index.js runs.  Recently it looks like the call from index.js to load both  (examples)
https://gibs.earthdata.nasa.gov/wms/epsg4326/best/wms.cgi?version=1.3.0&service=WMS&request=GetMap&format=image/png&STYLE=default&bbox=-90,-180,90,180&CRS=EPSG:4326&WIDTH=16384&HEIGHT=8192&TIME=2023-07-07&layers=VIIRS_NOAA20_Clear_Sky_Confidence_Day

https://gibs.earthdata.nasa.gov/wms/epsg4326/best/wms.cgi?version=1.3.0&service=WMS&request=GetMap&format=image/png&STYLE=default&bbox=-90,-180,90,180&CRS=EPSG:4326&WIDTH=16384&HEIGHT=8192&TIME=2023-07-07&layers=VIIRS_NOAA20_CorrectedReflectance_TrueColor

are taking quite a **long** time until the request is processed by Earthdata

Is there a way to modify the index.js to wait until the imagery is loaded before continuing?

**Comment by creinemann** [comment]
Matt, 
Some follow-up I got from NASA GIBS:
```
Hi Carl,

There are a few reasons why those downloads could be slow... for one, they're requesting images which are quite large (about 16k x 8k pixels) and WMS generally isn't a performant service. If you're looking to download large images rapidly, you might try something like a GDAL-based download which uses tile requests:
https://nasa-gibs.github.io/gibs-api-docs/map-library-usage/#gdal

Worldview also uses the WMTS tile-based access method which helps with performance.

Another possible reason is due to our current migration from an on premises system to the cloud. The WMS performance may get better over the course of the next few months.
```

**Comment by matteason** [comment]
Closing off as superseded by new service: https://github.com/matteason/live-cloud-maps
